CC          ?= cc
CXX         ?= c++
MKDIR_P     ?= mkdir -p
## COMMONFLAGS:
# -g is needed for debugging of any sort
# -DNOINSTALL sets the detected installation directory to the current directory (for easier debugging)
# -DDEBUG enables building and execution of the following tests:
# -DDEBUGATOM enables the Atom tests in Atom.Test.cpp
# -DDEBUGLOGGER enables the Logger test in Logger.Test.c (lots of output!)
# -DDEBUGMOTION enables the Motion object tests in Motion.Test.cpp
# -DDEBUGTICKER enables the Ticker object tests in Ticker.Test.cpp
# -DDEBUGTIMING enables the Timing function tests in Timing.Test.c
# -DDEBUGGEOMETRY enables the Geometry object tests in Geometry.Test.cpp
# -DDEBUGPLATFORM enables tests in Platform.Test.c
# -DDEBUGCONTAINER enables tests in Container.Test.cpp
# -DDEBUGVAR enables tests in Var.Test.cpp
# -DDEBUGVARSET enables tests in VarSet.Test.cpp
# -DDEBUGSMANIP enables tests in StringManip.Test.cpp
# -DDEBUGANIMATION enables tests in Animation.Test.cpp
# -DDEBUGANIMATIONSET enables tests in AnimationSet.Test.cpp
# -DDEBUGEXTRA enables extra output during tests
#COMMONFLAGS = -g -DDEBUG -DDEBUGATOM -DDEBUGLOGGER -DDEBUGMOTION -DDEBUGTICKER -DDEBUGTIMING -DDEBUGGEOMETRY \
	-DDEBUGPLATFORM -DDEBUGCONTAINER -DDEBUGVAR -DDEBUGVARSET -DDEBUGSMANIP -DDEBUGINTROSPECTOR -DDEBUGSENTENCE \
	-DDEBUGANIMATION -DDEBUGANIMATIONSET -DNOINSTALL -DDEBUGEXTRA
# add -fsanitize=address for ASAN
COMMONFLAGS ?= -g -DNOINSTALL -DDEBUG -DDEBUGPLATFORM -DDEBUGANIMATION -DDEBUGANIMATIONSET -DDEBUGEXTRA
CFLAGS      ?= $(COMMONFLAGS)
CXXFLAGS    ?= $(COMMONFLAGS)
CPPFLAGS    ?= -I./src/
#LDFLAGS     ?= -lasan -lpthread
LDFLAGS     ?= -lpthread

BUILD_DIR   ?=./build
SRC_DIR     ?=./src

### no easily-user-serviceable parts below this line

SRCS:=$(shell find $(SRC_DIR) -name *.cpp -or -name *.c)
OBJS:=$(SRCS:%=$(BUILD_DIR)/%.o)
DEPS:=$(OBJS:.o=.d)

$(BUILD_DIR)/%.c.o: %.c
	$(MKDIR_P) $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.cpp.o: %.cpp
	$(MKDIR_P) $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

$(BUILD_DIR)/iodine-test: $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)

bin:	$(BUILD_DIR)/iodine-test

doc:
	doxygen

all:	bin doc

.PHONY:	clean

clean:
	rm -rf build
	rm -rf doc
